language: ruby
rvm:
- 2.3.3

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

sudo: false

cache: pip
install:
  - pip install --user awscli

deploy:
  on:
    branch: master
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  skip_cleanup: true
  local_dir: _site
